const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000"

const normalizeScore = (value) => {
  if (value === undefined || value === null) return 0
  return value > 1 ? value / 100 : value
}

const formatRecommendationLabel = (value) => {
  const rec = String(value || "UNCERTAIN").toUpperCase()

  const labels = {
    BUY_NOW: "Buy Now",
    WAIT: "Wait",
    WAIT_WITH_CAUTION: "Wait with Caution",
    WAIT_AND_TRACK: "Wait and Track",
    UNCERTAIN: "Uncertain",
  }

  return labels[rec] || "Uncertain"
}

const normalizeRecommendation = (value) => {
  const rec = String(value || "UNCERTAIN").toUpperCase()

  if (rec === "BUY_NOW") return "buy"
  if (rec === "WAIT") return "wait"
  if (rec === "WAIT_WITH_CAUTION") return "wait_caution"
  if (rec === "WAIT_AND_TRACK") return "wait_track"

  return "uncertain"
}

const buildRecommendedWindow = (recommendation, bestHorizon) => {
  if (!bestHorizon) {
    return "Recommendation based on current price and availability signals"
  }

  if (recommendation === "WAIT_AND_TRACK") {
    return `Track the product over the next ${bestHorizon} days and buy when the price drops`
  }

  if (recommendation === "WAIT_WITH_CAUTION") {
    return `Wait up to ${bestHorizon} days, but monitor availability closely`
  }

  if (recommendation === "WAIT") {
    return `Waiting up to ${bestHorizon} days may be worthwhile`
  }

  if (recommendation === "BUY_NOW") {
    return "Buying now appears to be the safer option"
  }

  return "The model does not have enough confidence for a strong action"
}

const normalizeHorizonPredictions = (horizonPredictions = {}) => {
  return Object.entries(horizonPredictions).map(([key, value]) => ({
    key,
    horizon: value.horizon,
    probability: normalizeScore(value.price_drop_probability),
    price_zone: value.price_zone,
    buy_threshold: value.buy_threshold,
    wait_threshold: value.wait_threshold,
    recommendation_raw: value.recommendation,
    recommendation: normalizeRecommendation(value.recommendation),
    recommendation_label: formatRecommendationLabel(value.recommendation),
    explanation: value.explanation || [],
  }))
}

export const analyzeProduct = async (urlOrAsin) => {
  let response

  try {
    response = await fetch(`${API_BASE_URL}/predict`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        url_or_asin: urlOrAsin,
      }),
    })
  } catch {
    const error = new Error(
      "Unable to connect to the prediction service. Please check your connection or try again later."
    )
    error.status = 0
    throw error
  }

  if (!response.ok) {
    const errorData = await response.json().catch(() => null)

    const message =
      errorData?.detail ||
      errorData?.message ||
      `Request failed with status ${response.status}`

    const error = new Error(message)
    error.status = response.status
    throw error
  }

  const data = await response.json()

  const recommendation = normalizeRecommendation(data.recommendation)
  const priceDropProbability = normalizeScore(data.price_drop_probability)
  const horizonPredictions = normalizeHorizonPredictions(data.horizon_predictions)

  const explanationText = Array.isArray(data.explanation)
    ? data.explanation.join(" ")
    : data.explanation || "Recommendation generated by the prediction model."

  return {
    asin: data.asin,
    title: data.title || "Amazon Product",
    brand: data.brand || "Unknown brand",
    category: data.root_category || "Amazon Product",
    current_price: data.latest_price,
    latest_date: data.latest_date,
    image_url: data.image_url || "/src/assets/hero.png",

    recommendation,
    recommendation_raw: data.recommendation,
    recommendation_label: formatRecommendationLabel(data.recommendation),
    confidence: priceDropProbability || 0.5,
    best_horizon: data.best_horizon,

    recommended_window: buildRecommendedWindow(
      data.recommendation,
      data.best_horizon
    ),

    price_drop_probability: {
      days_7:
        horizonPredictions.find((item) => item.horizon === 7)?.probability || 0,
      days_14:
        horizonPredictions.find((item) => item.horizon === 14)?.probability || 0,
      days_30:
        horizonPredictions.find((item) => item.horizon === 30)?.probability || 0,
    },

    horizon_predictions: horizonPredictions,

    availability_risk: {
      level: data.availability_risk_level || "UNKNOWN",
      score: data.availability_risk_score ?? 0,
      flags: data.risk_flags || {},
    },

    reason: explanationText,
    explanation: data.explanation || [],

    top_factors: [
      {
        feature: "Selected price-drop window",
        effect: `${Math.round(priceDropProbability * 100)}% probability over ${data.best_horizon} days`,
      },
      {
        feature: "Availability risk",
        effect: `Risk level: ${data.availability_risk_level || "unknown"}`,
      },
      {
        feature: "Recommendation zone",
        effect: `Current zone: ${data.price_zone || "unknown"}`,
      },
    ],

    price_history: data.price_history || [],
  }
}
export const trackProduct = async (trackingData) => {
  let response

  try {
    response = await fetch(`${API_BASE_URL}/track`, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(trackingData),
    })
  } catch {
    const error = new Error(
      "Unable to connect to the tracking service. Please try again later."
    )
    error.status = 0
    throw error
  }

  if (!response.ok) {
    const errorData = await response.json().catch(() => null)

    const message =
      errorData?.detail ||
      errorData?.message ||
      `Tracking request failed with status ${response.status}`

    const error = new Error(message)
    error.status = response.status
    throw error
  }

  return response.json()
}

export const getTrackedProducts = async () => {
  const response = await fetch(`${API_BASE_URL}/tracking`)

  if (!response.ok) {
    throw new Error("Failed to load tracked products")
  }

  return await response.json()
}

export const stopTracking = async (trackingId) => {
  const response = await fetch(
    `${API_BASE_URL}/tracking/${trackingId}`,
    {
      method: "DELETE",
    }
  )

  if (!response.ok) {
    throw new Error("Failed to stop tracking")
  }

  return await response.json()
}