const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8000";

const normalizeScore = (value) => {
  if (value === undefined || value === null) return 0
  return value > 1 ? value / 100 : value
}

const normalizeRecommendation = (value) => {
  const rec = String(value || "uncertain").toLowerCase()

  if (rec === "buy_now" || rec === "buy now" || rec === "buy") {
    return "buy"
  }

  if (rec === "wait") {
    return "wait"
  }

  return "uncertain"
}

export const analyzeProduct = async (urlOrAsin) => {
  const response = await fetch(`${API_BASE_URL}/predict`, {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      url_or_asin: urlOrAsin,
    }),
  })

  if (!response.ok) {
    const errorData = await response.json().catch(() => null)

    throw new Error(
      errorData?.detail || "Failed to analyze product"
    )
  }

  const data = await response.json()

  const recommendation = normalizeRecommendation(data.recommendation)

  const explanationText = Array.isArray(data.explanation)
    ? data.explanation.join(" ")
    : data.explanation || "Recommendation generated by the prediction model."

  const priceDropProbability = normalizeScore(data.price_drop_probability)
  const availabilityRisk = normalizeScore(data.availability_risk_score)

  return {
    asin: data.asin,
    title: data.title || "Amazon Product",
    brand: data.brand || "Unknown brand",
    category: data.root_category || "Amazon Product",
    current_price: data.latest_price,
    image_url: data.image_url || "/src/assets/hero.png",

    recommendation,
    confidence: priceDropProbability || 0.5,

    recommended_window:
      recommendation === "wait"
        ? "Waiting may be beneficial"
        : recommendation === "buy"
        ? "Buying now may be reasonable"
        : "No strong recommendation",

    price_drop_probability: {
      days_7: priceDropProbability,
      days_14: priceDropProbability,
      days_30: priceDropProbability,
    },

    availability_risk: {
      days_7: availabilityRisk,
      days_14: availabilityRisk,
      days_30: availabilityRisk,
    },

    reason: explanationText,

    top_factors: [
      {
        feature: "Price-drop probability",
        effect: `Estimated probability: ${Math.round(priceDropProbability * 100)}%`,
      },
      {
        feature: "Availability risk",
        effect: `Risk level: ${data.availability_risk_level || "unknown"}`,
      },
      {
        feature: "Price zone",
        effect: `Current zone: ${data.price_zone || "unknown"}`,
      },
    ],

    price_history: data.price_history || [],
  }
}